version: '3.4'

services:

  nginx:
    build: './nginx'
    container_name: nginx
    networks:
      - ${NETWORK}
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - mysql
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/supervisord.conf:/etc/supervisord.conf

      - ./phpmyadmin/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.com.conf

      - ./sites/ebncana.com/conf/ebncana.com.conf:/etc/nginx/conf.d/ebncana.com.conf
      - ./sites/ebncana.com/public:/var/www/ebncana.com/public

      - ./sites/localhost/conf/localhost.conf:/etc/nginx/conf.d/localhost.conf
      - ./sites/localhost/public:/var/www/html

  apache:
    build: './apache'
    container_name: apache
    networks:
      - ${NETWORK}
    ports:
      - "8080:80"
    links:
      - php
      - mysql
    volumes:
      - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf

      - ./sites/localhost/vhosts/localhost.conf:/usr/local/apache2/conf/vhosts/localhost.conf
      - ./sites/localhost/public:/var/www/html
      
      - ./sites/germanautoexport.localhost/vhosts/germanautoexport.localhost.conf:/usr/local/apache2/conf/vhosts/germanautoexport.localhost.conf
      - ./sites/germanautoexport.localhost/public:/var/www/germanautoexport.localhost/public


  mysql:
    build: './mysql'
    container_name: mysql
    networks:
      - ${NETWORK}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_DEFAULT_USER}
      MYSQL_PASSWORD: ${MYSQL_DEFAULT_PASSWORD}

  phpmyadmin:
    build: './phpmyadmin'
    container_name: phpmyadmin
    networks:
      - ${NETWORK}
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=mysql
    restart: always
    depends_on:
    - mysql

  php:
    build: './php'
    container_name: php
    networks:
      - ${NETWORK}
    ports:
      - "9000:9000"
    volumes:
      - ./sites/ebncana.com/public:/var/www/ebncana.com/public
      - ./sites/germanautoexport.localhost/public:/var/www/germanautoexport.localhost/public
      - ./sites/localhost/public:/var/www/html

networks:
    webserver:
        external: true
